// Generated by `supabase gen types typescript --local` — do not hand-edit.
// Regenerate after every migration (see CLAUDE.md conventions). Hand-derived
// here from supabase/migrations/*.sql since this repo has no live Supabase
// project yet to generate against; shape matches the CLI output format so a
// real `supabase gen types` run is a drop-in replacement.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          handle: string;
          display_name: string;
          created_at: string;
        };
        Insert: {
          id: string;
          handle: string;
          display_name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          handle?: string;
          display_name?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      bets: {
        Row: {
          id: string;
          creator_id: string;
          parent_bet_id: string | null;
          title: string;
          description: string | null;
          status: Database['public']['Enums']['bet_status'];
          visibility: Database['public']['Enums']['bet_visibility'];
          resolution_method: Database['public']['Enums']['resolution_method'];
          locks_at: string;
          created_at: string;
          published_at: string | null;
        };
        Insert: {
          id?: string;
          creator_id: string;
          parent_bet_id?: string | null;
          title: string;
          description?: string | null;
          status?: Database['public']['Enums']['bet_status'];
          visibility?: Database['public']['Enums']['bet_visibility'];
          resolution_method?: Database['public']['Enums']['resolution_method'];
          locks_at: string;
          created_at?: string;
          published_at?: string | null;
        };
        Update: {
          id?: string;
          creator_id?: string;
          parent_bet_id?: string | null;
          title?: string;
          description?: string | null;
          status?: Database['public']['Enums']['bet_status'];
          visibility?: Database['public']['Enums']['bet_visibility'];
          resolution_method?: Database['public']['Enums']['resolution_method'];
          locks_at?: string;
          created_at?: string;
          published_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'bets_creator_id_fkey';
            columns: ['creator_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'bets_parent_bet_id_fkey';
            columns: ['parent_bet_id'];
            referencedRelation: 'bets';
            referencedColumns: ['id'];
          },
        ];
      };
      outcomes: {
        Row: {
          id: string;
          bet_id: string;
          label: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          bet_id: string;
          label: string;
          sort_order: number;
        };
        Update: {
          id?: string;
          bet_id?: string;
          label?: string;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'outcomes_bet_id_fkey';
            columns: ['bet_id'];
            referencedRelation: 'bets';
            referencedColumns: ['id'];
          },
        ];
      };
      positions: {
        Row: {
          id: string;
          bet_id: string;
          user_id: string;
          outcome_id: string;
          stake_kind: Database['public']['Enums']['stake_kind'];
          stake_label: string;
          accepted_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          bet_id: string;
          user_id: string;
          outcome_id: string;
          stake_kind: Database['public']['Enums']['stake_kind'];
          stake_label: string;
          accepted_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          bet_id?: string;
          user_id?: string;
          outcome_id?: string;
          stake_kind?: Database['public']['Enums']['stake_kind'];
          stake_label?: string;
          accepted_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'positions_bet_id_fkey';
            columns: ['bet_id'];
            referencedRelation: 'bets';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'positions_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'positions_outcome_id_fkey';
            columns: ['outcome_id'];
            referencedRelation: 'outcomes';
            referencedColumns: ['id'];
          },
        ];
      };
      clauses: {
        Row: {
          id: string;
          position_id: string;
          condition_text: string;
          effect_kind: Database['public']['Enums']['stake_kind'];
          effect_label: string;
          triggered: boolean | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          position_id: string;
          condition_text: string;
          effect_kind: Database['public']['Enums']['stake_kind'];
          effect_label: string;
          triggered?: boolean | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          position_id?: string;
          condition_text?: string;
          effect_kind?: Database['public']['Enums']['stake_kind'];
          effect_label?: string;
          triggered?: boolean | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'clauses_position_id_fkey';
            columns: ['position_id'];
            referencedRelation: 'positions';
            referencedColumns: ['id'];
          },
        ];
      };
      predictions: {
        Row: {
          id: string;
          bet_id: string;
          user_id: string;
          outcome_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          bet_id: string;
          user_id: string;
          outcome_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          bet_id?: string;
          user_id?: string;
          outcome_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'predictions_bet_id_fkey';
            columns: ['bet_id'];
            referencedRelation: 'bets';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'predictions_outcome_id_fkey';
            columns: ['outcome_id'];
            referencedRelation: 'outcomes';
            referencedColumns: ['id'];
          },
        ];
      };
      resolutions: {
        Row: {
          id: string;
          bet_id: string;
          status: Database['public']['Enums']['resolution_status'];
          declared_outcome_id: string | null;
          declared_by: string | null;
          declared_at: string | null;
          confirmed_at: string | null;
          auto_void_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          bet_id: string;
          status?: Database['public']['Enums']['resolution_status'];
          declared_outcome_id?: string | null;
          declared_by?: string | null;
          declared_at?: string | null;
          confirmed_at?: string | null;
          auto_void_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          bet_id?: string;
          status?: Database['public']['Enums']['resolution_status'];
          declared_outcome_id?: string | null;
          declared_by?: string | null;
          declared_at?: string | null;
          confirmed_at?: string | null;
          auto_void_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'resolutions_bet_id_fkey';
            columns: ['bet_id'];
            referencedRelation: 'bets';
            referencedColumns: ['id'];
          },
        ];
      };
      resolution_responses: {
        Row: {
          id: string;
          resolution_id: string;
          user_id: string;
          response: Database['public']['Enums']['resolution_response_kind'];
          reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          resolution_id: string;
          user_id: string;
          response: Database['public']['Enums']['resolution_response_kind'];
          reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          resolution_id?: string;
          user_id?: string;
          response?: Database['public']['Enums']['resolution_response_kind'];
          reason?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'resolution_responses_resolution_id_fkey';
            columns: ['resolution_id'];
            referencedRelation: 'resolutions';
            referencedColumns: ['id'];
          },
        ];
      };
      settlements: {
        Row: {
          id: string;
          bet_id: string;
          losing_position_id: string;
          winning_position_id: string;
          owed_by: string;
          owed_to: string;
          stake_label: string;
          paid_at: string | null;
          confirmed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          bet_id: string;
          losing_position_id: string;
          winning_position_id: string;
          owed_by: string;
          owed_to: string;
          stake_label: string;
          paid_at?: string | null;
          confirmed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          bet_id?: string;
          losing_position_id?: string;
          winning_position_id?: string;
          owed_by?: string;
          owed_to?: string;
          stake_label?: string;
          paid_at?: string | null;
          confirmed_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'settlements_bet_id_fkey';
            columns: ['bet_id'];
            referencedRelation: 'bets';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'settlements_losing_position_id_fkey';
            columns: ['losing_position_id'];
            referencedRelation: 'positions';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'settlements_winning_position_id_fkey';
            columns: ['winning_position_id'];
            referencedRelation: 'positions';
            referencedColumns: ['id'];
          },
        ];
      };
      bet_events: {
        Row: {
          id: string;
          bet_id: string;
          kind: Database['public']['Enums']['bet_event_kind'];
          actor_id: string | null;
          body: string | null;
          payload: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          bet_id: string;
          kind: Database['public']['Enums']['bet_event_kind'];
          actor_id?: string | null;
          body?: string | null;
          payload?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          bet_id?: string;
          kind?: Database['public']['Enums']['bet_event_kind'];
          actor_id?: string | null;
          body?: string | null;
          payload?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'bet_events_bet_id_fkey';
            columns: ['bet_id'];
            referencedRelation: 'bets';
            referencedColumns: ['id'];
          },
        ];
      };
      reactions: {
        Row: {
          id: string;
          event_id: string;
          user_id: string;
          emoji: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          user_id: string;
          emoji: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          user_id?: string;
          emoji?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'reactions_event_id_fkey';
            columns: ['event_id'];
            referencedRelation: 'bet_events';
            referencedColumns: ['id'];
          },
        ];
      };
      point_ledger: {
        Row: {
          id: string;
          user_id: string;
          bet_id: string;
          points: number;
          reason: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          bet_id: string;
          points: number;
          reason: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          bet_id?: string;
          points?: number;
          reason?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'point_ledger_bet_id_fkey';
            columns: ['bet_id'];
            referencedRelation: 'bets';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      leaderboard: {
        Row: {
          user_id: string | null;
          handle: string | null;
          display_name: string | null;
          total_points: number | null;
          scored_predictions: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      can_view_bet: {
        Args: { p_bet_id: string; p_user_id: string | null };
        Returns: boolean;
      };
      is_bet_participant: {
        Args: { p_bet_id: string; p_user_id: string | null };
        Returns: boolean;
      };
      award_prediction_points: {
        Args: { p_bet_id: string };
        Returns: undefined;
      };
      lock_expired_bets: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      void_expired_resolutions: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
    };
    Enums: {
      bet_status: 'draft' | 'open' | 'locked' | 'resolved' | 'voided';
      bet_visibility: 'private' | 'invite' | 'public';
      resolution_method: 'unanimous' | 'creator' | 'majority';
      stake_kind: 'cash_offline' | 'food_drink' | 'favour' | 'item' | 'bragging_rights';
      resolution_status: 'pending' | 'declared' | 'confirmed' | 'disputed' | 'void';
      resolution_response_kind: 'confirm' | 'dispute';
      bet_event_kind:
        | 'bet_created'
        | 'position_accepted'
        | 'clause_added'
        | 'bet_locked'
        | 'outcome_declared'
        | 'resolution_confirmed'
        | 'resolution_disputed'
        | 'stake_settled'
        | 'message';
    };
  };
};

type PublicSchema = Database['public'];

export type Tables<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Row'];
export type TablesInsert<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T]['Update'];
export type Enums<T extends keyof PublicSchema['Enums']> = PublicSchema['Enums'][T];
